version: 2

sources:

  # =====================
  # RAW / BRONZE LAYER
  # =====================
  - name: raw
    schema: raw
    description: "Raw ingested data from source systems"
    tables:
      - name: customers
        description: "Raw customer data as ingested from source system"
        columns:
          - name: customer_id
            tests:
              - not_null
              - unique

          - name: signup_date
            tests:
              - not_null

  # =====================
  # STAGING / SILVER INPUT
  # =====================
  - name: staging
    schema: staging
    description: "Cleaned and standardized staging tables"
    tables:
      - name: customer
        description: "Staged customer data with cleaned columns"
        columns:
          - name: customer_id
            tests:
              - not_null
              - unique

          - name: registration_date
            tests:
              - not_null

  # =====================
  # MARTS / GOLD INPUT
  # =====================
  - name: marts
    schema: marts
    description: "Business-ready fact and dimension tables"
    tables:
      - name: fct_customer_registration
        description: "Fact table for customer registrations"
        columns:
          - name: registration_month
            tests:
              - not_null

          - name: customer_count
            tests:
              - not_null
